server:
  port: 8090

spring:
  profiles:
    active: default
  application:
    name: monicar-emulator

logging:
  config: classpath:logback-spring-dev.xml
  file:
    path: ./logs

api:
  transmission-time: 60
  base-url: http://localhost:8082/api/v1/event-hub/
  # 에뮬레이터를 컨테이너로 만든 상태에서 로컬 event-hub 서버에 요청 보낼 때
#  base-url: http://host.docker.internal:8082/api/v1/event-hub/

file-name: default_seoul-to-gyeongju_formatted.gpx

fixed:
  vehicle-mdn: 1234567890
  vehicle-number: 123나1234

---
server:
  port: 8091

spring:
  config:
    activate:
      on-profile: tomato
  application:
    name: monicar-emulator-tomato

file-name: tomato_yangyang-to-daegu_formatted.gpx

# rds vehicle_information 데이터 기준
fixed:
  vehicle-mdn: 2254690422
  vehicle-number: 657가5202

---
server:
  port: 8092

spring:
  config:
    activate:
      on-profile: banana
  application:
    name: monicar-emulator-banana

file-name: banana_yeosu-to-cheonan_formatted.gpx

# rds vehicle_information 데이터 기준
fixed:
  vehicle-mdn: 5246479703
  vehicle-number: 309가9777

---
server:
  port: 8093

spring:
  config:
    activate:
      on-profile: apple
  application:
    name: monicar-emulator-apple

file-name: apple_gwangju-to-muju_formatted.gpx

# rds vehicle_information 데이터 기준
fixed:
  vehicle-mdn: 6459804235
  vehicle-number: 530가4820

---
server:
  port: 8094

spring:
  config:
    activate:
      on-profile: peach
  application:
    name: monicar-emulator-peach

file-name: peach_suwon-daejon-gumi-optimized.gpx

# rds vehicle_information 데이터 기준
fixed:
  vehicle-mdn: 3831511086
  vehicle-number: 401다5889